pipeline {
    agent any
    stages {
        stage('Build, Package & Tag') {
            steps {
                withCredentials([file(credentialsId: 'env-vars-zoo-fe', variable: 'env_file')]) {
                    writeFile file: 'src/assets/.env', text: readFile(env_file)
                }
                sh '''BRANCH=$(echo $GIT_BRANCH | cut -b 8-11)
                docker build -t frontend-zoo-$BRANCH:1.0.0-$BUILD_ID .'''
            }
        }
        stage('Deploy') {
          
          steps {
            script {
              def remote = [:]
          remote.name = "server"
          remote.host = "0.tcp.ngrok.io"
              remote.port = 14925
          remote.allowAnyHosts = true
              withCredentials([usernamePassword(credentialsId: 'ssh-credentials-vm', passwordVariable: 'pass', usernameVariable: 'userName')]) {
                    remote.user = userName
                    remote.password = pass
                    writeFile file: 'abc.sh', text: 'ls'
                    sshCommand remote: remote, command: 'for i in {1..5}; do echo -n \"Loop \$i \"; date ; sleep 1; done'
                    sshCommand remote: remote, command: 'cd /home/tony/deploy_00/devops-frontend;git checkout develop;git pull origin develop; ng build'
                    sshCommand remote: remote, command: 'ls -la'
                 
                }
            }
                  
            }
        }
    }
}
