pipeline {
    agent any
    stages {
        stage('Build, Package & Tag') {
            steps {
                sh 'echo "Deploying to VM, Skipping this stage."'
            }
        }
        stage('Deploy') {
          
          steps {
            script {
              def remote = [:]
          remote.name = "server"
          remote.host = "0.tcp.ngrok.io"
              remote.port = 14925
          remote.allowAnyHosts = true
              withCredentials([usernamePassword(credentialsId: 'ssh-credentials-vm', passwordVariable: 'pass', usernameVariable: 'userName')]) {
                    remote.user = userName
                    remote.password = pass
                    sshCommand remote: remote, command: "bash /home/tony/deploy.sh"
                 
                }
            }
                  
            }
        }
    }
}
